# These settings are just used when running in dev mode; production mode uses the statically compiled artifacts
[serve]
address = "127.0.0.1"
port = 9090

[[proxy]]
backend = "http://localhost:9091/api/"